- name: add golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present

- name: add go and cli into $PATH
  lineinfile:
    path: /etc/profile
    line: export PATH=$PATH:/usr/local/go/bin:/root/go/bin

- name: install golang
  unarchive:
    src: https://dl.google.com/go/go1.17.linux-amd64.tar.gz
    dest : /usr/local
    remote_src: yes

- name: create temporary cli container
  docker_container:
    name: temp_data_container
    image: projecteru2/cli
    state: present
    volumes:
      - your_data_volume:/data

- name: install cli
  command: docker cp temp_data_container:/usr/bin/eru-cli /usr/local/bin

- name: install cli lib
  command: docker cp temp_data_container:/lib/ld-musl-x86_64.so.1 /lib

- name: remove temporary cli container
  docker_container:
    name: temp_data_container
    state: absent
