- name: eru add docker pod
  delegate_to: "{{ core_host }}"
  shell: eru-cli pod add docker

- name: eru add node
  delegate_to: "{{ core_host }}"
  shell: eru-cli node add --nodename {{ node_docker_name }} --endpoint tcp://{{ inventory_hostname }}:2377 docker
  register: res
  failed_when: res.rc != 0 and 'Key exists' not in res.stderr

- name: mkdir /etc/eru
  file:
    path: /etc/eru/
    state: directory

- name: render eru agent
  template:
    src: eru-agent.yaml.j2
    dest: /etc/eru/agent.yaml

- name: run eru agent
  delegate_to: "{{ core_host }}"
  shell: eru-cli workload deploy --pod docker --node {{ node_docker_name }} --entry agent --file /etc/eru/agent.yaml:/agent.yaml --network host --image projecteru2/agent --cpu-request 0 --memory-request 0 --memory-limit 0 --env ERU_HOSTNAME={{ node_docker_name }} https://raw.githubusercontent.com/projecteru2/agent/master/spec.yaml
